on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit
        id: latest_commit
        run: |
          latest_commit=$(git log -1 --pretty=format:"%H")
          echo "COMMIT_ID=$latest_commit" >> $GITHUB_ENV

      - name: Make POST request
        run: |
          echo "Commit ID: $COMMIT_ID"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"head_commit":{"id": "'$COMMIT_ID'"} }' \
            "https://develop-api.zendata.dev/scans/300b9f94-e095-4cdc-aa71-66c783d0075e/callback/"
